version: 0.0
os: linux
files:
  - source: dist/my-angular-project
    destination: /var/www/html/my-angular-project
permissions:
  - object: /var/www/html
    pattern: '**'
    mode: '0755'
    owner: root
    group: root
    type:
      - file
      - directory